### PR TITLE
Limit switch

### PR DESCRIPTION
**Pull request by yycho0108**
LimitSwitch

### CODE REVIEW

**Comment by HALtheWise** [comment]
Should we wait to pull this into master until it has been tested?

**Comment by eschneider1992** [comment]
If it hasn't been tested, then we should wait. I wasn't sure of its status.
Thanks

**Comment by HALtheWise** [comment]
Also, we should check on why there is a Serial.begin() in setup(). I'm not sure it belongs there.

**Comment by eschneider1992** [comment]
I'm pretty sure Serial.begin(*baud_rate*) is supposed to go into setup() if
you're using regular serial communication, I'm not sure where it should go
if rosserial is being used

**Comment by HALtheWise** [comment]
Ultimately, it turns out that the Jaguar's inbuilt support for limit switches is sophisticated enough to allow us to automatically stop the motor's motion in only one direction. This largely removes the need for software-based limit switches, although we should leave this branch around in case it becomes useful on some other actuator in the future and/or reading the limit switches proves convenient so that software knows why / if an actuator isn't moving.

**Pull request closed without merging**
